spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miniproject_likelion
    username: root
    password:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace